# Generated by Django 5.2.8 on 2025-11-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=150)),
                ('CategoryParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='Store.category')),
            ],
            options={
                'verbose_name': 'CategoryName',
                'verbose_name_plural': 'Categories',
                'unique_together': {('CategoryParent',)},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=150)),
                ('ProductDescription', models.TextField(max_length=150)),
                ('ProductQuantity', models.IntegerField(default=0)),
                ('ProductPrice', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ProductCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.category')),
            ],
        ),
    ]
