# Generated by Django 5.2.8 on 2025-11-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductImage',
            field=models.ImageField(null=True, upload_to='uploads/images/'),
        ),
    ]
