# Generated by Django 5.2.8 on 2025-11-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductNew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductSale',
            field=models.BooleanField(default=False),
        ),
    ]
