# Generated by Django 5.2.8 on 2025-11-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_product_productnew_product_productsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductStar',
            field=models.IntegerField(default=1),
        ),
    ]
